### ISSUE TITLE
Error: Input required and not supplied: key  ( from actions/cache@v2 )

### ISSUE THREAD

**Issue by LaurentDardenne** [potatoqualitee/psmodulecache#24]
I try to use psmodulecache but I get [an error](https://github.com/LaurentDardenne/EtsDateTime/runs/7342412066?check_suite_focus=true) :
![image](https://user-images.githubusercontent.com/4894452/179014207-0a9d1386-924e-44ef-8940-67baaf0637ae.png)

I'm new to Github Action, I don't know if it's [my script](https://github.com/LaurentDardenne/EtsDateTime/blob/master/.github/workflows/Build.yml) that's wrong (it's very likely) or if there's a problem with PSModulecache.

I was inspired by [this example](https://scriptingchris.tech/posts/how-to-setup-a-github-actions-pipeline-for-publishing-your-powershell-module/#setting-up-the-required-powershell-modules-in-the-pipeline). I couldn't find a (beginner's) demo in the PSModuleCache documentation.

My goal being to use 'actions/cache@v3' for Windows Powershell only.

**Comment by potatoqualitee** [comment]
Hey @LaurentDardenne! Your code mixes and matches versions. You only need this now:

```
- name: Set required PowerShell modules
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v4.5

        with:
          modules-to-cache: PSScriptAnalyzer, InvokeBuild, platyPS
          shell: powershell
```

This will install those modules for PowerShell (5.1) and not pwsh (7+). Pester is already installed so you don't need it on the list.

Let me know if it helps.

You can also check out the repo and see all the tests I do with each commit.

https://github.com/potatoqualitee/psmodulecache/blob/main/.github/workflows/test.yml#L134
