### ISSUE TITLE
Restoring a cache throws an error on tar.exe

### ISSUE THREAD

**Issue by LaurentDardenne** [potatoqualitee/psmodulecache#26]
The creation and use of the cache works : 
![image](https://user-images.githubusercontent.com/4894452/179351371-e4e84274-c5f5-4925-b23f-098da0bc1a6c.png)

But generates an error when restoring:
![image](https://user-images.githubusercontent.com/4894452/179351124-3c2a0b71-58a8-420f-b0cf-f6db1062c128.png)
![image](https://user-images.githubusercontent.com/4894452/179351270-9497e34f-8024-4ac3-ac5d-1d98ff505a79.png)

The build of the cache seems to integrate pre-existing files into the image of the selected host.

Can using the [exclude pattern](https://github.com/actions/cache/search?q=exclude) on the _Path_ parameter solve this problem?

**Comment by LaurentDardenne** [comment]
The source of the problem may be here:
![image](https://user-images.githubusercontent.com/4894452/179357407-b2e0de2b-fa04-4a7c-92a3-d411e6a017c6.png)

According to the [cache action documentation](https://github.com/actions/cache#inputs) : 
![image](https://user-images.githubusercontent.com/4894452/179357551-f0e20dfd-a115-494f-9612-77a8146a5aa9.png)
This parameter should contain the list of module directories to cache and not just the parent directory.
By doing so it will still be possible to save modules that are not installed in the default directory (PsGallery)

**Comment by LaurentDardenne** [comment]
A priori by modifying [this line](https://github.com/potatoqualitee/psmodulecache/blob/main/action.yml#L41) like this, solves the problem :

```powershell
 Write-Output "::set-output name=modulepath::$($modulepath| ConvertTo-JSON -Compress)"
```

**Comment by LaurentDardenne** [comment]
Array elements should be separated by '%0A' as shown [here](https://github.com/orgs/community/discussions/26288).
Before passing the contents of the Action/Cache.Path parameter, the Runner transforms '%0A' into "`n" and finally the cache code [splits the chain](https://github.com/actions/cache/blob/main/src/utils/actionUtils.ts#L63).
It's almost esoteric...
```yaml
            Write-Output "::set-output name=modulepath::C:\Program Files\WindowsPowerShell\Modules\PnP.PowerShell%0AC:\Program Files\WindowsPowerShell\Modules\InvokeBuild"
            
      - name: Setup PowerShell module cache (Set required PowerShell modules)
        id: cacher
        uses: actions/cache@v2
        with:
          path: |
              ${{ steps.psrepo.outputs.modulepath }}
          key: ${{ runner.os }}-Test-PSModuleCache
```
First call (with Action/cache globbing) :
![image](https://user-images.githubusercontent.com/4894452/181734382-72b0b6de-b14d-4927-82e2-a661fe111d35.png)

Second call :
![image](https://user-images.githubusercontent.com/4894452/181734934-3fb89022-80db-4f94-93c9-74ce1d225bfd.png)

I will continue my tests to confirm this.
