### ISSUE TITLE
Question about the second example of the readme.txt

### ISSUE THREAD

**Issue by LaurentDardenne** [potatoqualitee/psmodulecache#30]
I do not understand the description of the second example of the readme.txt :

_Using powershell on Windows. pwsh also works and is the default._

```yaml

on: [push]

jobs:
  run-on-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install and cache PowerShell modules
      id: psmodulecache
      uses: potatoqualitee/psmodulecache@v4.5
      with:
        modules-to-cache: PSFramework, PoshRSJob, dbatools:1.0.0
    - name: Show that the Action works
      shell: pwsh
      run: |
          Get-Module -Name PSFramework, PoshRSJob, dbatools -ListAvailable | Select Path

```
The 'powershell' shell is not used and the shell parameter of the psmodulecache action is missing, by default the 'pswh' shell is used.
Is this a mistake or do I need to improve my[ googlish](https://translate.google.fr/)?

![image](https://user-images.githubusercontent.com/4894452/183247996-5b99634d-6df6-443f-865b-b1daf3a92a6e.png)
