### ISSUE TITLE
Warning: Path Validation Error

### ISSUE THREAD

**Issue by niheaven** [potatoqualitee/psmodulecache#38]
> Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.

I've met the above warning in a post step, so what's wrong?

My GHA yml is as following:

```yml
jobs:
  test_powershell:
    name: WindowsPowerShell
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 2
      - name: Init Test Suite
        uses: potatoqualitee/psmodulecache@v5.1
        with:
          modules-to-cache: PSScriptAnalyzer, BuildHelpers, Pester
          shell: powershell
```

The warnings are the same for powershell or pwsh shell.
