### ISSUE TITLE
Action fails when used with a container job

### ISSUE THREAD

**Issue by flcdrg** [potatoqualitee/psmodulecache#43]
Given the following workflow:

```yaml
name: Cache Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/powershell:ubuntu-22.04
    steps:

      - uses: actions/checkout@v3

      - name: PowerShell Module Cache
        uses: potatoqualitee/psmodulecache@v5.2
        with:
          modules-to-cache: Az.Network
```

The action fails:
![image](https://user-images.githubusercontent.com/384747/210121182-99034bda-c4d6-4cb1-9d19-8d7acdc32a69.png)

Here's the full output from the action:

```text
Run potatoqualitee/psmodulecache@v5.2
  with:
    modules-to-cache: Az.Network
    shell: pwsh
    updatable: false
    prefixidentifier: false
Run Import-Module /home/runner/work/_actions/potatoqualitee/psmodulecache/v5.2/PSModuleCache.psd1
  Import-Module /home/runner/work/_actions/potatoqualitee/psmodulecache/v5.2/PSModuleCache.psd1
  Write-Output "Getting variables for cacher"
  
  $Parameters = @{
    Modules = "Az.Network"
    PrereleaseModules = ""
    Shells = "pwsh"
    Updatable = [boolean]::Parse("false")
    PrefixIdentifier = [boolean]::Parse("false")
  }
  Write-Output "Action Parameters = $([PsCustomObject]$Parameters)"
  
  $ActionParameters = New-ModuleCacheParameter @Parameters
  
  $ModuleCaches = Get-ModuleCache $ActionParameters
  "keygen=$($ModuleCaches.Key)" >> $env:GITHUB_OUTPUT
  
  $Paths = @(New-ModuleSavePath $ModuleCaches.ModuleCacheInformations)
  
  # Accommodate multi-line
  "modulepath<<EOF" >> $env:GITHUB_OUTPUT
  $Paths >> $env:GITHUB_OUTPUT
  "EOF" >> $env:GITHUB_OUTPUT
  
  $null = $ModuleCaches | Export-CliXml -Path (Join-Path $home -ChildPath $CacheFileName)
  shell: pwsh -command ". '{0}'"
  
Import-Module: /__w/_temp/393f6afa-82ee-45c2-8362-0fdf70641abd.ps1:2
Line |
   2 |  Import-Module /home/runner/work/_actions/potatoqualitee/psmodulecache …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The specified module
     | '/home/runner/work/_actions/potatoqualitee/psmodulecache/v5.2/PSModuleCache.psd1' was not loaded because no valid module file was found in any module directory.
Error: Process completed with exit code 1.
```
