### ISSUE TITLE
Get parsing error when using `::` without version on `modules-to-cache`

### ISSUE THREAD

**Issue by johlju** [potatoqualitee/psmodulecache#47]
I get and error when using this configuration. Shoukd it be wriiten differently? 

```
      - name: PowerShell Module Cache
        uses: potatoqualitee/psmodulecache@v5.2
        with:
          modules-to-cache: PSScriptAnalyzer::, ConvertToSARIF::
          allow-prerelease: false
          updatable: true
```

Gives the error

 
![image](https://user-images.githubusercontent.com/7189721/222920544-5c02c3aa-0f34-44a7-9808-dcd51795def2.png)
