### ISSUE TITLE
Problems with Microsoft.Powershell.SecretManagement

### ISSUE THREAD

**Issue by Callidus2000** [potatoqualitee/psmodulecache#48]
Hi,
I'm using your action for my validation and build workflows. My current module needs the following dependencies:
`RestartableSession,PSFramework,string,PSModuleDevelopment,Microsoft.Powershell.SecretManagement,ChangelogManagement`

First run (building the cache) works, afterwards (relying on the cache) everythings works but `Microsoft.Powershell.SecretManagement` is missing.

In the first run the workflow 
```
Run potatoqualitee/psmodulecache@main
Run Import-Module $env:GITHUB_ACTION_PATH/PSModuleCache.psd1
Getting variables for cacher
Action Parameters = @{Modules=RestartableSession,PSFramework,string,PSModuleDevelopment,Microsoft.Powershell.SecretManagement,ChangelogManagement; PrefixIdentifier=False; PrereleaseModules=; ContainerJob=False; Updatable=False; Shells=pwsh}
Run actions/cache@v3.0.11
Cache not found for input keys: Linux-5.2-Immutable-pwsh-RestartableSession-PSFramework-string-PSModuleDevelopment-Microsoft.Powershell.SecretManagement-ChangelogManagement
Run Write-Output "Saving all modules"
Saving all modules
Existing repositories 'PSGallery'
Saving module 'RestartableSession' version '' to '/usr/local/share/powershell/Modules/'. Search in the following repositories 'PSGallery'
	Module 'RestartableSession' version '0.4.0' found in 'PSGallery'.
Saving module 'PSFramework' version '' to '/usr/local/share/powershell/Modules/'. Search in the following repositories 'PSGallery'
	Module 'PSFramework' version '1.7.270' found in 'PSGallery'.
Saving module 'string' version '' to '/usr/local/share/powershell/Modules/'. Search in the following repositories 'PSGallery'
	Module 'string' version '1.1.3' found in 'PSGallery'.
Saving module 'PSModuleDevelopment' version '' to '/usr/local/share/powershell/Modules/'. Search in the following repositories 'PSGallery'
	Module 'PSModuleDevelopment' version '2.2.11.139' found in 'PSGallery'.
Saving module 'Microsoft.Powershell.SecretManagement' version '' to '/usr/local/share/powershell/Modules/'. Search in the following repositories 'PSGallery'
	Module 'Microsoft.PowerShell.SecretManagement' version '1.1.2' found in 'PSGallery'.
Saving module 'ChangelogManagement' version '' to '/usr/local/share/powershell/Modules/'. Search in the following repositories 'PSGallery'
	Module 'ChangelogManagement' version '3.0.1' found in 'PSGallery'.
```

second run
```
Run potatoqualitee/psmodulecache@main
Run Import-Module $env:GITHUB_ACTION_PATH/PSModuleCache.psd1
Getting variables for cacher
Action Parameters = @{Updatable=False; ContainerJob=False; Shells=pwsh; Modules=RestartableSession,PSFramework,string,PSModuleDevelopment,Microsoft.Powershell.SecretManagement,ChangelogManagement; PrereleaseModules=; PrefixIdentifier=False}
Run actions/cache@v3.0.11
Received 1505700 of 1505700 (100.0%), 13.1 MBs/sec
Cache Size: ~1 MB (1505700 B)
/usr/bin/tar -z -xf /home/runner/work/_temp/a65b75ea-18d9-4d13-8796-a24caf52dbc2/cache.tgz -P -C /home/runner/work/SecretManagement.ExtensionTemplate/SecretManagement.ExtensionTemplate
Cache restored successfully
Cache restored from key: Linux-5.2-Immutable-pwsh-RestartableSession-PSFramework-string-PSModuleDevelopment-Microsoft.Powershell.SecretManagement-ChangelogManagement
```

**Comment by LaurentDardenne** [comment]
Module dependencies are not managed today, I'm testing [this part](https://github.com/LaurentDardenne/psmodulecache/blob/FeatureModuleDependencies/test/GHA.PSmoduleCache.Dependency.Tests.ps1). I plan to deliver within a month, maybe less.


As PSModuleCache allows to address several repositories, I have to check different use cases.
I encounter some bugs on PsGet, for example if there are redundant modules in several repositories, _Find-module -IncludeDepencies_ returns the dependencies according to the order of declarations of PSRepositories and the external dependencies are not raised by _Find-module -IncludeDepencies_.

For the moment to correct this problem, it is necessary to explain the dependent modules in the parameters of the action.

**Comment by Callidus2000** [comment]
Sorry, chosen the wrong word...
My module requires `Microsoft.Powershell.SecretManagement`
```Powershell
    RequiredModules   = @(@{ModuleName = 'RestartableSession'; ModuleVersion = '0.4.0'; },
        @{ModuleName = 'PSFramework'; ModuleVersion = '1.7.249'; },
        @{ModuleName = 'string'; ModuleVersion = '1.0.0'; },
        @{ModuleName = 'PSModuleDevelopment'; ModuleVersion = '2.2.11'; },
        @{ModuleName = 'Microsoft.Powershell.SecretManagement'; ModuleVersion = '1.1.2'; })
```
and uses in the workflow yaml
```YAML
- name: Install and cache PowerShell modules
  id: psmodulecache
  uses: potatoqualitee/psmodulecache@v5.2
  with:
    modules-to-cache: RestartableSession,PSFramework,string,PSModuleDevelopment,Microsoft.Powershell.SecretManagement,ChangelogManagement
```
Found out the hardway that dependencies are (currently) not been dealt with, thats why I've added `string` as a direkt module.

Therefor dependency was wrong, the required module ist not preserved in the cache.

Taking a look at one of the debug logs
[11_Install and cache PowerShell modules.txt](https://github.com/potatoqualitee/psmodulecache/files/10978742/11_Install.and.cache.PowerShell.modules.txt)

I've seen that in the `tar` call only the other paths are mentioned:
- usr/local/share/powershell/Modules/RestartableSession/
- usr/local/share/powershell/Modules/PSFramework/
- usr/local/share/powershell/Modules/string/
- usr/local/share/powershell/Modules/PSModuleDevelopment/
- usr/local/share/powershell/Modules/ChangelogManagement/
- usr/local/share/powershell/Modules/platyPS/

**Comment by LaurentDardenne** [comment]
>>I've seen that in the tar call only the other paths are mentioned

The management of '.' (dot char) is taken into account when generating the key and the path is inserted in the list of paths to be saved by Tar.
I need to test this case on Linux and Windows.

**Comment by LaurentDardenne** [comment]
I have no problem [with](https://github.com/LaurentDardenne/psmodulecache/blob/FeatureModuleDependencies/.github/workflows/MatrixCacheForIssue.yml) this syntax (Ubuntu):
```yaml
      - name: Cache modules
        id: psmodulecache
        uses: ./
        with:
          modules-to-cache: RestartableSession,PSFramework,string,PSModuleDevelopment,Microsoft.Powershell.SecretManagement,ChangelogManagement
          shell: powershell,pwsh
          updatable: "false"

      - name: Get required modules on Windows PowerShell
        shell: pwsh
        run: |
          'RestartableSession','PSFramework','string','PSModuleDevelopment','Microsoft.Powershell.SecretManagement','ChangelogManagement'|
          foreach {
             Import-Module $_
             Write-Host "$_ '$(Get-Module $_ -ListAvailabLe|Select-Object Name,Version,@{Name='PreRelease';e={$_.PrivateData.PSData.Prerelease}},RepositorySourceLocation)'"
          }
```

![image](https://user-images.githubusercontent.com/4894452/225315369-9ce4cf54-a3b6-41a0-963d-c470e24396c5.png)

But I haven't tested with this syntax (dynamic search for module dependencies), like you do in your workflow :
```yaml
    - name: Query needed modules
      id: getReqModules
      shell: pwsh
      run: |
          "RequiredModules=$((Import-PowerShellDataFile "./$($env:MODULENAME)/$($env:MODULENAME).psd1").RequiredModules.modulename -join ',')" >> $env:GITHUB_OUTPUT
          # (Import-PowerShellDataFile ./SecretManagement.ExtensionTemplate/SecretManagement.ExtensionTemplate.psd1).RequiredModules.modulename -join ','
    - name: Install and cache PowerShell modules
      id: psmodulecache
      uses: potatoqualitee/psmodulecache@main
      with:
        modules-to-cache: ${{ steps.getReqModules.outputs.RequiredModules }},ChangelogManagement
```

**Comment by LaurentDardenne** [comment]
Can you test with this order of dependencies?
```powershell
 RequiredModules   = @(@{ModuleName = 'RestartableSession'; ModuleVersion = '0.4.0'; },
        @{ModuleName = 'PSFramework'; ModuleVersion = '1.7.249'; },
        @{ModuleName = 'PSModuleDevelopment'; ModuleVersion = '2.2.11'; },
        @{ModuleName = 'Microsoft.Powershell.SecretManagement'; ModuleVersion = '1.1.2'; },
        @{ModuleName = 'string'; ModuleVersion = '1.0.0'; })
```

**Comment by Callidus2000** [comment]
Tested, same behavior, works once (as key changes), further iterations fail.

**Comment by Callidus2000** [comment]
Cut down my workflow to non fancyness:
```Yaml
name: CheckOnPR-Module-Debug
on: 
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
jobs:
  CheckOnPR-Module-Debug:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
    - name: Install and cache PowerShell modules
      id: psmodulecache
      uses: potatoqualitee/psmodulecache@main
      with:
        modules-to-cache: RestartableSession,PSFramework,string,PSModuleDevelopment,Microsoft.Powershell.SecretManagement,ChangelogManagement
        updatable: "false"
        shell: powershell,pwsh
    - name: Make sure modules are installed
      shell: pwsh
      run: |
        'RestartableSession','PSFramework','string','PSModuleDevelopment','Microsoft.Powershell.SecretManagement','ChangelogManagement'|
        foreach {
            Write-Host "$_ '$(Get-Module $_ -ListAvailabLe|Select-Object Name,Version,@{Name='PreRelease';e={$_.PrivateData.PSData.Prerelease}},RepositorySourceLocation)'"
            Import-Module $_
        } 
    - name: Setup tmate session
      # if: ${{ failure() || (github.event_name == 'workflow_dispatch' && inputs.debug_enabled ) }}
      if: ${{ (github.event_name == 'workflow_dispatch' && inputs.debug_enabled ) }}
      uses: mxschmitt/action-tmate@v3
```
But the result from the second run on is the same:
```
Run 'RestartableSession','PSFramework','string','PSModuleDevelopment','Microsoft.Powershell.SecretManagement','ChangelogManagement'|
  'RestartableSession','PSFramework','string','PSModuleDevelopment','Microsoft.Powershell.SecretManagement','ChangelogManagement'|
  foreach {
      Write-Host "$_ '$(Get-Module $_ -ListAvailabLe|Select-Object Name,Version,@{Name='PreRelease';e={$_.PrivateData.PSData.Prerelease}},RepositorySourceLocation)'"
      Import-Module $_
  } 
  shell: /usr/bin/pwsh -command ". '{0}'"
RestartableSession '@{Name=RestartableSession; Version=0.4.0; PreRelease=; RepositorySourceLocation=https://www.powershellgallery.com/api/v2}'
PSFramework '@{Name=PSFramework; Version=[1](https://github.com/Callidus2000/SecretManagement.ExtensionTemplate/actions/runs/4438613010/jobs/7789907683#step:3:1).7.[2](https://github.com/Callidus2000/SecretManagement.ExtensionTemplate/actions/runs/4438613010/jobs/7789907683#step:3:2)70; PreRelease=; RepositorySourceLocation=https://www.powershellgallery.com/api/v2}'
string '@{Name=string; Version=1.1.[3](https://github.com/Callidus2000/SecretManagement.ExtensionTemplate/actions/runs/4438613010/jobs/7789907683#step:3:3); PreRelease=; RepositorySourceLocation=https://www.powershellgallery.com/api/v2}'
PSModuleDevelopment '@{Name=PSModuleDevelopment; Version=2.2.11.139; PreRelease=; RepositorySourceLocation=https://www.powershellgallery.com/api/v2}'
Microsoft.Powershell.SecretManagement ''
Import-Module: /home/runner/work/_temp/5bb[4](https://github.com/Callidus2000/SecretManagement.ExtensionTemplate/actions/runs/4438613010/jobs/7789907683#step:3:4)03bb-9281-4bb4-a[5](https://github.com/Callidus2000/SecretManagement.ExtensionTemplate/actions/runs/4438613010/jobs/7789907683#step:3:5)16-da6f5b4603b5.ps1:5
Line |
   5 |      Import-Module $_
     |      ~~~~~~~~~~~~~~~~
     | The specified module 'Microsoft.Powershell.SecretManagement' was not
     | loaded because no valid module file was found in any module directory.
```
