### ISSUE TITLE
Dependent modules no longer cached (v5.1 onwards)

### ISSUE THREAD

**Issue by christianacca** [potatoqualitee/psmodulecache#50]
As of version 5.1, it appears only those modules directly referenced in the `modules-to-cache` list are cached, the module dependencies are no longer cached.

This was not the case with v4.5 which cached not only the modules listed in `modules-to-cache`, but also the dependencies of those modules.

Take the following usage of v4.5:

```yaml
      - name: 'Install dependent powershell modules'
        uses: potatoqualitee/psmodulecache@v4.5
        with:
          modules-to-cache: Az:9.3.0,SqlServer:22.0.59
```

The above produces a cache that I believe includes the dependencies of the `Az` module (eg `Az.Accounts`). Note the size of the cache:

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/886590/235486369-dfdae364-c182-4720-88da-59bde8424edd.png">

On a subsequent execution of the workflow that includes the caching step, the cache is resolved and the workflow is able to import the powershell modules that it needs.

Take the following usage of v5.3:

```yaml
      - name: 'Install dependent powershell modules'
        uses: potatoqualitee/psmodulecache@03c44cade706c982e0632f52a2712668b03c8f24 # <- 5.3
        with:
          modules-to-cache: Az:9.3.0,SqlServer:22.0.59
```

The above produces a cache that I believe does NOT include the dependencies of the `Az` module (eg `Az.Accounts`). Note the size of the cache which is much smaller than the same cache when using v4.5:

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/886590/235486038-763ee4d9-eb61-4e6d-933c-0fdd154a4b54.png">

On a subsequent execution of the workflow that includes the caching step, the cache is resolved but the workflow fails to import one of the _dependent_ powershell modules that it needs (see below screenshot). The ONLY difference between the example above and this example, is the version of potatoqualitee/psmodulecache

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/886590/235486546-aceee122-4296-4e2a-9b83-ab5fb7d5ef69.png">
